@startgantt projectplan

Project starts the 4th of may 2020
saturday are closed
sunday are closed

[Prototype design] lasts 3 days
[Screen design] lasts 5 days
[Credential 1 data model] lasts 5 days
[Testing] lasts 10 days

[Credential transfer QR] lasts 15 days
[Verification embedded credential] lasts 5 days


[Prototype design]->[Testing]
[Prototype design]->[Screen design]
[Prototype design]->[Credentials data model]


@endgantt